"""empty message

Revision ID: b45bf8478254
Revises: 776cd5fdda3d
Create Date: 2021-12-06 23:51:19.473073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45bf8478254'
down_revision = '776cd5fdda3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=64), nullable=True),
    sa.Column('genres', sa.String(length=64), nullable=True),
    sa.Column('artist_url', sa.String(length=128), nullable=True),
    sa.Column('img_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('artist_id'),
    sa.UniqueConstraint('artist_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    # ### end Alembic commands ###
