"""Creating Track's model

Revision ID: ce0a729ea659
Revises: 208ac7a33836
Create Date: 2022-01-04 16:50:41.118265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0a729ea659'
down_revision = '208ac7a33836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=64), nullable=False),
    sa.Column('album_name', sa.String(length=64), nullable=False),
    sa.Column('track_name', sa.String(length=64), nullable=False),
    sa.Column('track_img_url', sa.String(length=128), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('track_url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    # ### end Alembic commands ###
